version: '3'

services:

  # npm
  npm:
    build: ./npm
    volumes:
      - ${APPLICATION}:/var/www/html:cached
      - ~/.ssh/:/root/.ssh/:cached
    environment:
      - CHANGE_SOURCE=${CHANGE_SOURCE}
      - PORT=${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    tty: true
